env:
    - SMVERSION=1.6
    - SMVERSION=1.7
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.7
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null
    - sudo apt-get update -qq > /dev/null
    - sudo apt-get -qq update && sudo apt-get install gcc-multilib lynx lib32stdc++6 -y
install:
    - SMPATTERN="http:.*sourcemod-.*-git.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - ASHERKINURL="http://builds.limetech.org/files/"
    - TF2ITEMSPATTERN="http:.*tf2items-.*-.*-linux.zip"
    - TF2ITEMSPACKAGE=`lynx -dump "$ASHERKINURL" | egrep -o "$TF2ITEMSPATTERN" | tail -1`
    - wget $TF2ITEMSPACKAGE
    - unzip $(basename "$TF2ITEMSPACKAGE")
    - STEAMTOOLSPATTERN="http:.*steamtools-.*-git.*-.*-linux.zip"
    - STEAMTOOLSPACKAGE=`lynx -dump "$ASHERKINURL" | egrep -o "$STEAMTOOLSPATTERN" | tail -1`
    - wget $STEAMTOOLSPACKAGE
    - unzip $(basename "$STEAMTOOLSPACKAGE")
    - cd addons/sourcemod
before_script:
    - cd ./scripting/
    - wget "https://www.doctormckay.com/download/scripting/include/morecolors.inc"
    - mv morecolors.inc include/
    - chmod +x spcomp
    - mkdir compiled
script: ./compile.sh saxtonhale.sp

#Notifications
notifications:
    email: false
