env:
    - SMVERSION=1.7
    - SMVERSION=1.8
matrix:
  fast_finish: true
  allow_failures:
    - env: SMVERSION=1.8
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test > /dev/null
    - sudo apt-get update -qq > /dev/null
    - sudo apt-get install gcc-multilib lynx lib32stdc++6 -y  > /dev/null
install:
    - SMPATTERN="http:.*sourcemod-.*-git.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$SMVERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cd addons/sourcemod
before_script:
    - cd ./scripting/include/
    - wget "https://forums.alliedmods.net/attachment.php?attachmentid=141740" -O morecolors.inc
    - wget "http://hg.limetech.org/projects/tf2items/tf2items_source/raw-file/tip/pawn/tf2items.inc" -O tf2items.inc
    - wget "https://code.limetech.org/diffusion/ST/browse/master/plugin/steamtools.inc?view=raw" -O steamtools.inc
    - cd ../
    - chmod +x spcomp
    - mkdir compiled
script: ./compile.sh saxtonhale.sp

#Notifications
notifications:
    email: false
